{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: requests in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (2.30.0)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests) (2.0.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests) (2023.5.7)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests) (3.4)\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")) - skipping\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pandas in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (1.5.3)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from pandas) (1.24.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from pandas) (2022.7.1)\n",
      "Requirement already satisfied: six>=1.5 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")) - skipping\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: beautifulsoup4 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (4.11.2)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Users/sanghu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from beautifulsoup4) (2.4)\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")) - skipping\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")': /simple/boto3/\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")': /simple/boto3/\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")': /simple/boto3/\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")': /simple/boto3/\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")': /simple/boto3/\u001b[0m\u001b[33m\n",
      "\u001b[0mCould not fetch URL https://pypi.org/simple/boto3/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/boto3/ (Caused by SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")) - skipping\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement boto3 (from versions: none)\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[31mERROR: No matching distribution found for boto3\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[33mWARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.\u001b[0m\u001b[33m\n",
      "\u001b[0mCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(\"Can't connect to HTTPS URL because the SSL module is not available.\")) - skipping\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install requests\n",
    "%pip install pandas\n",
    "%pip install beautifulsoup4\n",
    "%pip install boto3\n",
    "# %pip install logging"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'boto3'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 6\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtime\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01muuid\u001b[39;00m\n\u001b[0;32m----> 6\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mboto3\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mio\u001b[39;00m\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mlogging\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'boto3'"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import time\n",
    "import uuid\n",
    "import boto3\n",
    "import io\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(level='DEBUG')\n",
    "\n",
    "header = {'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '\n",
    "                         '(KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'),}\n",
    "\n",
    "session = boto3.Session(\n",
    "    aws_access_key_id='AKIA4SZHNYWTL3EDJVMJ',\n",
    "    aws_secret_access_key='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',\n",
    "    region_name='ap-northeast-2'\n",
    ")\n",
    "\n",
    "s3 = session.resource('s3')\n",
    "bucket_name = 'newsseug-bucket'\n",
    "\n",
    "categories = {\n",
    "    '정치': 'https://www.joongang.co.kr/politics',\n",
    "    '경제': 'https://www.joongang.co.kr/money',\n",
    "    '국제': 'https://www.joongang.co.kr/world',\n",
    "    '사회': 'https://www.joongang.co.kr/society/accident', # 앞 분기 기준\n",
    "    '경제': 'https://www.joongang.co.kr/money/science' # 앞 분기 기준\n",
    "}\n",
    "\n",
    "def scrap_article(article_url, category):\n",
    "    response = requests.get(article_url)\n",
    "    soup = BeautifulSoup(response.text, 'html.parser')\n",
    "\n",
    "    try:\n",
    "        category = soup.find('a', {'class': 'title'}).get_text(strip=True)\n",
    "        \n",
    "        # 카테고리가 아닌 글은 패스\n",
    "        if category != category:\n",
    "            logging.info(f\"{article_url} 는 해당 카테고리가 아니어서 생략합니다. \")\n",
    "            return None\n",
    "    except AttributeError:\n",
    "        logging.error(f\"{article_url} 는 찾을 수 없습니다.\")\n",
    "        return None\n",
    "\n",
    "    # 헤드라인 스크랩\n",
    "    try:\n",
    "        headline = soup.find('h1', {'class': 'headline'}).get_text(strip=True)\n",
    "    except AttributeError:\n",
    "        headline = 'N/A'\n",
    "\n",
    "    # 생성일 스크랩\n",
    "    try:\n",
    "        date = soup.find('p', {'class': 'date'})\n",
    "        time = date.find('time').get('datetime')\n",
    "    except AttributeError:\n",
    "        time = 'N/A'\n",
    "\n",
    "    # 본문 스크랩\n",
    "    try:\n",
    "        content = soup.find('div', {'class': 'article_body'}).get_text(strip=True)\n",
    "    except AttributeError:\n",
    "        content = 'N/A'\n",
    "\n",
    "    # 기자 이름 스크랩\n",
    "    try:\n",
    "        byline = soup.find('div', {'class': 'byline'})\n",
    "        reporter = byline.find('a').get_text(strip=True).split('\\n')[0]\n",
    "    except AttributeError:\n",
    "        reporter = 'N/A'\n",
    "\n",
    "    return {'headline': headline, 'time': time, 'content': content, 'reporter': reporter}\n",
    "\n",
    "def save_article_to_s3(article_data, category):\n",
    "    file_name = str(uuid.uuid4()) + '.json'\n",
    "\n",
    "    article_df = pd.DataFrame([article_data])\n",
    "\n",
    "    buffer = io.StringIO()\n",
    "    article_df.to_json(buffer, orient='records', lines=True, force_ascii=False)\n",
    "\n",
    "    buffer.seek(0)\n",
    "    \n",
    "    try:\n",
    "        # s3.put_object(Bucket=bucket_name, Key=f'content/{file_name}', Body=buffer.getvalue())\n",
    "        s3.Bucket(bucket_name).put_object(Key=f'content/joongang/{category}/{file_name}', Body=buffer.getvalue())\n",
    "        logging.debug(f\"{file_name} 을 {category}/{bucket_name} 에 업로드 하였습니다.\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Error uploading {file_name}: {e}\")\n",
    "\n",
    "def check_for_new_articles(base_url, category):\n",
    "    response = requests.get(base_url)\n",
    "    soup = BeautifulSoup(response.text, 'html.parser')\n",
    "\n",
    "    cards = soup.find_all('li', class_='card')\n",
    "    for card in cards:\n",
    "        article_link = card.find('a', href=True)['href']\n",
    "        logging.debug(f\"Scraping article: {article_link}\")\n",
    "\n",
    "        result = scrap_article(article_link, category)\n",
    "\n",
    "        if result is None:\n",
    "            continue\n",
    "\n",
    "        save_article_to_s3(result, category)\n",
    "\n",
    "def scrap_all_categories():\n",
    "    \n",
    "    for category, base_url in categories.items():\n",
    "        logging.info(f\"category (base_url): {category} ({base_url})\")\n",
    "        check_for_new_articles(base_url, category)\n",
    "        time.sleep(2)\n",
    "\n",
    "scrap_all_categories()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
